all:
	mkdir -p /usr/local/www/wsgi-scripts
	install -o nagios -g nagios pre-onboarding.py /usr/local/www/wsgi-scripts/pre-onboarding.wsgi
	install -o nagios -g nagios index.thtml /usr/local/www/wsgi-scripts/index.thtml